**1_Importing Pandas**

In [2]:
import pandas as pd

**2_Reading csv file**

In [3]:
df=pd.read_csv('employees_data.csv')
print(df)

    EmployeeID     Name Department  Salary  Age       City
0            1      Ali         HR   45000   24   Peshawar
1            2    Ahmad         IT   52000   25  Islamabad
2            3    Usman    Finance   48000   26     Lahore
3            4    Bilal  Marketing   55000   27    Karachi
4            5    Hamza         IT   60000   28   Peshawar
5            6     Saad         HR   47000   24     Mardan
6            7  Zeeshan    Finance   51000   29       Swat
7            8    Ahsan  Marketing   53000   30  Charsadda
8            9    Fahad         IT   62000   26  Islamabad
9           10    Talha         HR   49000   25   Peshawar
10          11      Ali    Finance   50000   27     Lahore
11          12    Ahmad  Marketing   56000   28    Karachi
12          13    Usman         IT   64000   29   Peshawar
13          14    Bilal         HR   46000   24     Mardan
14          15    Hamza    Finance   52000   30       Swat
15          16     Saad  Marketing   57000   26  Charsadda
16          17  Zeeshan         IT   65000   27  Islamabad
17          18    Ahsan         HR   48000   28   Peshawar
18          19    Fahad    Finance   53000   29     Lahore
19          20    Talha  Marketing   58000   30    Karachi
20          21      Ali         IT   61000   25   Peshawar
21          22    Ahmad         HR   47000   26     Mardan
22          23    Usman    Finance   54000   27       Swat
23          24    Bilal  Marketing   59000   28  Charsadda
24          25    Hamza         IT   66000   29  Islamabad
25          26     Saad         HR   49000   24   Peshawar
26          27  Zeeshan    Finance   55000   30     Lahore
27          28    Ahsan  Marketing   60000   26    Karachi
28          29    Fahad         IT   67000   27   Peshawar
29          30    Talha         HR   50000   28     Mardan
30          31      Ali    Finance   56000   29       Swat
31          32    Ahmad  Marketing   61000   30  Charsadda
32          33    Usman         IT   68000   25  Islamabad
33          34    Bilal         HR   51000   26   Peshawar
34          35    Hamza    Finance   57000   27     Lahore
35          36     Saad  Marketing   62000   28    Karachi
36          37  Zeeshan         IT   69000   29   Peshawar
37          38    Ahsan         HR   52000   30     Mardan
38          39    Fahad    Finance   58000   25       Swat
39          40    Talha  Marketing   63000   26  Charsadda
40          41      Ali         IT   70000   27  Islamabad
41          42    Ahmad         HR   53000   28   Peshawar
42          43    Usman    Finance   59000   29     Lahore
43          44    Bilal  Marketing   64000   30    Karachi
44          45    Hamza         IT   71000   25   Peshawar
45          46     Saad         HR   54000   26     Mardan
46          47  Zeeshan    Finance   60000   27       Swat
47          48    Ahsan  Marketing   65000   28  Charsadda
48          49    Fahad         IT   72000   29  Islamabad
49          50    Talha         HR   55000   30   Peshawar

**3_Printing first fivw rows**

In [4]:
df.head(5)

   EmployeeID   Name Department  Salary  Age       City
0           1    Ali         HR   45000   24   Peshawar
1           2  Ahmad         IT   52000   25  Islamabad
2           3  Usman    Finance   48000   26     Lahore
3           4  Bilal  Marketing   55000   27    Karachi
4           5  Hamza         IT   60000   28   Peshawar

**4_Printing last five rows**

In [5]:
df.tail(5)

    EmployeeID     Name Department  Salary  Age       City
45          46     Saad         HR   54000   26     Mardan
46          47  Zeeshan    Finance   60000   27       Swat
47          48    Ahsan  Marketing   65000   28  Charsadda
48          49    Fahad         IT   72000   29  Islamabad
49          50    Talha         HR   55000   30   Peshawar

**5_Total rows and columns**

In [6]:
df.shape

(50, 6)

**6_Column names**

In [7]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Salary', 'Age', 'City'], dtype='str')

**7_Data types**

In [8]:
df.dtypes

EmployeeID    int64
Name            str
Department      str
Salary        int64
Age           int64
City            str
dtype: object

**8_Overall information**

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  50 non-null     int64
 1   Name        50 non-null     str
 2   Department  50 non-null     str
 3   Salary      50 non-null     int64
 4   Age         50 non-null     int64
 5   City        50 non-null     str
dtypes: int64(3), str(3)
memory usage: 3.3 KB

**9_Numerical summary**

In [10]:
df.describe()

       EmployeeID        Salary        Age
count    50.00000     50.000000  50.000000
mean     25.50000  57180.000000  27.320000
std      14.57738   7136.254091   1.889174
min       1.00000  45000.000000  24.000000
25%      13.25000  52000.000000  26.000000
50%      25.50000  56500.000000  27.000000
75%      37.75000  62000.000000  29.000000
max      50.00000  72000.000000  30.000000

**10_finding missing values**

In [11]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Salary        0
Age           0
City          0
dtype: int64

**10_A single and multiple columns**

In [15]:
df["Age"]

0     24
1     25
2     26
3     27
4     28
5     24
6     29
7     30
8     26
9     25
10    27
11    28
12    29
13    24
14    30
15    26
16    27
17    28
18    29
19    30
20    25
21    26
22    27
23    28
24    29
25    24
26    30
27    26
28    27
29    28
30    29
31    30
32    25
33    26
34    27
35    28
36    29
37    30
38    25
39    26
40    27
41    28
42    29
43    30
44    25
45    26
46    27
47    28
48    29
49    30
Name: Age, dtype: int64

In [16]:
df[['Name','Age']]

       Name  Age
0       Ali   24
1     Ahmad   25
2     Usman   26
3     Bilal   27
4     Hamza   28
5      Saad   24
6   Zeeshan   29
7     Ahsan   30
8     Fahad   26
9     Talha   25
10      Ali   27
11    Ahmad   28
12    Usman   29
13    Bilal   24
14    Hamza   30
15     Saad   26
16  Zeeshan   27
17    Ahsan   28
18    Fahad   29
19    Talha   30
20      Ali   25
21    Ahmad   26
22    Usman   27
23    Bilal   28
24    Hamza   29
25     Saad   24
26  Zeeshan   30
27    Ahsan   26
28    Fahad   27
29    Talha   28
30      Ali   29
31    Ahmad   30
32    Usman   25
33    Bilal   26
34    Hamza   27
35     Saad   28
36  Zeeshan   29
37    Ahsan   30
38    Fahad   25
39    Talha   26
40      Ali   27
41    Ahmad   28
42    Usman   29
43    Bilal   30
44    Hamza   25
45     Saad   26
46  Zeeshan   27
47    Ahsan   28
48    Fahad   29
49    Talha   30

**11_total rows and total columns**

In [13]:
df.shape[0]

50

In [14]:
df.shape[1]

6

**12_value count**

In [17]:
df['Department'].value_counts()

Department
HR           13
IT           13
Finance      12
Marketing    12
Name: count, dtype: int64

**13_specific row ,range and many specific rows**

In [26]:
df.iloc[10]

EmployeeID           16
Name               Saad
Department    Marketing
Salary            57000
Age                  26
City          Charsadda
Name: 10, dtype: object

In [27]:
df.iloc[[10,20,30]]

    EmployeeID  Name Department  Salary  Age       City
10          16  Saad  Marketing   57000   26  Charsadda
20          26  Saad         HR   49000   24   Peshawar
30          36  Saad  Marketing   62000   28    Karachi

In [29]:
df.iloc[10:20]

    EmployeeID     Name Department  Salary  Age       City
10          16     Saad  Marketing   57000   26  Charsadda
11          17  Zeeshan         IT   65000   27  Islamabad
12          18    Ahsan         HR   48000   28   Peshawar
13          19    Fahad    Finance   53000   29     Lahore
14          20    Talha  Marketing   58000   30    Karachi
15          21      Ali         IT   61000   25   Peshawar
16          22    Ahmad         HR   47000   26     Mardan
17          23    Usman    Finance   54000   27       Swat
18          24    Bilal  Marketing   59000   28  Charsadda
19          25    Hamza         IT   66000   29  Islamabad

**14_filter data from columns**

In [35]:
df[df["Age"]<25]

    EmployeeID   Name Department  Salary  Age      City
2            6   Saad         HR   47000   24    Mardan
8           14  Bilal         HR   46000   24    Mardan
20          26   Saad         HR   49000   24  Peshawar

In [37]:
df[df["Department"]=="IT"]

    EmployeeID     Name Department  Salary  Age       City
0            2    Ahmad         IT   52000   25  Islamabad
7           13    Usman         IT   64000   29   Peshawar
11          17  Zeeshan         IT   65000   27  Islamabad
15          21      Ali         IT   61000   25   Peshawar
19          25    Hamza         IT   66000   29  Islamabad
23          29    Fahad         IT   67000   27   Peshawar
27          33    Usman         IT   68000   25  Islamabad
31          37  Zeeshan         IT   69000   29   Peshawar
35          41      Ali         IT   70000   27  Islamabad
39          45    Hamza         IT   71000   25   Peshawar
43          49    Fahad         IT   72000   29  Islamabad

**15_SELF TEST**

In [39]:
df=pd.read_csv('employees_data.csv')

In [40]:
df.head(5)

   EmployeeID   Name Department  Salary  Age       City
0           1    Ali         HR   45000   24   Peshawar
1           2  Ahmad         IT   52000   25  Islamabad
2           3  Usman    Finance   48000   26     Lahore
3           4  Bilal  Marketing   55000   27    Karachi
4           5  Hamza         IT   60000   28   Peshawar

In [41]:
df.tail(10)

    EmployeeID     Name Department  Salary  Age       City
40          41      Ali         IT   70000   27  Islamabad
41          42    Ahmad         HR   53000   28   Peshawar
42          43    Usman    Finance   59000   29     Lahore
43          44    Bilal  Marketing   64000   30    Karachi
44          45    Hamza         IT   71000   25   Peshawar
45          46     Saad         HR   54000   26     Mardan
46          47  Zeeshan    Finance   60000   27       Swat
47          48    Ahsan  Marketing   65000   28  Charsadda
48          49    Fahad         IT   72000   29  Islamabad
49          50    Talha         HR   55000   30   Peshawar

In [43]:
df.shape

(50, 6)

In [44]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Salary', 'Age', 'City'], dtype='str')

In [49]:
df.dtypes

EmployeeID    int64
Name            str
Department      str
Salary        int64
Age           int64
City            str
dtype: object

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  50 non-null     int64
 1   Name        50 non-null     str
 2   Department  50 non-null     str
 3   Salary      50 non-null     int64
 4   Age         50 non-null     int64
 5   City        50 non-null     str
dtypes: int64(3), str(3)
memory usage: 3.3 KB

In [52]:
df.describe()

       EmployeeID        Salary        Age
count    50.00000     50.000000  50.000000
mean     25.50000  57180.000000  27.320000
std      14.57738   7136.254091   1.889174
min       1.00000  45000.000000  24.000000
25%      13.25000  52000.000000  26.000000
50%      25.50000  56500.000000  27.000000
75%      37.75000  62000.000000  29.000000
max      50.00000  72000.000000  30.000000

In [55]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Salary        0
Age           0
City          0
dtype: int64

In [56]:
df["Age"]

0     24
1     25
2     26
3     27
4     28
5     24
6     29
7     30
8     26
9     25
10    27
11    28
12    29
13    24
14    30
15    26
16    27
17    28
18    29
19    30
20    25
21    26
22    27
23    28
24    29
25    24
26    30
27    26
28    27
29    28
30    29
31    30
32    25
33    26
34    27
35    28
36    29
37    30
38    25
39    26
40    27
41    28
42    29
43    30
44    25
45    26
46    27
47    28
48    29
49    30
Name: Age, dtype: int64

In [57]:
df[['Name','Age']]

       Name  Age
0       Ali   24
1     Ahmad   25
2     Usman   26
3     Bilal   27
4     Hamza   28
5      Saad   24
6   Zeeshan   29
7     Ahsan   30
8     Fahad   26
9     Talha   25
10      Ali   27
11    Ahmad   28
12    Usman   29
13    Bilal   24
14    Hamza   30
15     Saad   26
16  Zeeshan   27
17    Ahsan   28
18    Fahad   29
19    Talha   30
20      Ali   25
21    Ahmad   26
22    Usman   27
23    Bilal   28
24    Hamza   29
25     Saad   24
26  Zeeshan   30
27    Ahsan   26
28    Fahad   27
29    Talha   28
30      Ali   29
31    Ahmad   30
32    Usman   25
33    Bilal   26
34    Hamza   27
35     Saad   28
36  Zeeshan   29
37    Ahsan   30
38    Fahad   25
39    Talha   26
40      Ali   27
41    Ahmad   28
42    Usman   29
43    Bilal   30
44    Hamza   25
45     Saad   26
46  Zeeshan   27
47    Ahsan   28
48    Fahad   29
49    Talha   30

In [58]:
df.sample(5)

    EmployeeID     Name Department  Salary  Age       City
24          25    Hamza         IT   66000   29  Islamabad
46          47  Zeeshan    Finance   60000   27       Swat
39          40    Talha  Marketing   63000   26  Charsadda
1            2    Ahmad         IT   52000   25  Islamabad
32          33    Usman         IT   68000   25  Islamabad

In [61]:
df.shape[0]

50

In [62]:
df.shape[1]

6

In [63]:
df.iloc[1]

EmployeeID            2
Name              Ahmad
Department           IT
Salary            52000
Age                  25
City          Islamabad
Name: 1, dtype: object

In [64]:
df.iloc[0:10]

   EmployeeID     Name Department  Salary  Age       City
0           1      Ali         HR   45000   24   Peshawar
1           2    Ahmad         IT   52000   25  Islamabad
2           3    Usman    Finance   48000   26     Lahore
3           4    Bilal  Marketing   55000   27    Karachi
4           5    Hamza         IT   60000   28   Peshawar
5           6     Saad         HR   47000   24     Mardan
6           7  Zeeshan    Finance   51000   29       Swat
7           8    Ahsan  Marketing   53000   30  Charsadda
8           9    Fahad         IT   62000   26  Islamabad
9          10    Talha         HR   49000   25   Peshawar

In [65]:
df.iloc[10:15]

    EmployeeID   Name Department  Salary  Age      City
10          11    Ali    Finance   50000   27    Lahore
11          12  Ahmad  Marketing   56000   28   Karachi
12          13  Usman         IT   64000   29  Peshawar
13          14  Bilal         HR   46000   24    Mardan
14          15  Hamza    Finance   52000   30      Swat

In [70]:
df.iloc[0,0]

np.int64(1)

In [71]:
df.iloc[0,1]

'Ali'

In [72]:
df.iloc[:,0]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
35    36
36    37
37    38
38    39
39    40
40    41
41    42
42    43
43    44
44    45
45    46
46    47
47    48
48    49
49    50
Name: EmployeeID, dtype: int64

In [73]:
df.iloc[:,1]

0         Ali
1       Ahmad
2       Usman
3       Bilal
4       Hamza
5        Saad
6     Zeeshan
7       Ahsan
8       Fahad
9       Talha
10        Ali
11      Ahmad
12      Usman
13      Bilal
14      Hamza
15       Saad
16    Zeeshan
17      Ahsan
18      Fahad
19      Talha
20        Ali
21      Ahmad
22      Usman
23      Bilal
24      Hamza
25       Saad
26    Zeeshan
27      Ahsan
28      Fahad
29      Talha
30        Ali
31      Ahmad
32      Usman
33      Bilal
34      Hamza
35       Saad
36    Zeeshan
37      Ahsan
38      Fahad
39      Talha
40        Ali
41      Ahmad
42      Usman
43      Bilal
44      Hamza
45       Saad
46    Zeeshan
47      Ahsan
48      Fahad
49      Talha
Name: Name, dtype: str

In [74]:
df.iloc[0:3,0:2]

   EmployeeID   Name
0           1    Ali
1           2  Ahmad
2           3  Usman