***1_importing libraries and dataset***

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    'Date': ['2026-01-15', '2026-02-20', '2026-03-10',
             '2026-04-25', '2026-05-05'],
    'Time': ['09:30:00', '14:45:00', '18:20:00',
             '10:15:00', '21:50:00'],
    'Sales': [2000, 3500, 1800, 4200, 3000]
})
df.head()

         Date      Time  Sales
0  2026-01-15  09:30:00   2000
1  2026-02-20  14:45:00   3500
2  2026-03-10  18:20:00   1800
3  2026-04-25  10:15:00   4200
4  2026-05-05  21:50:00   3000

In [3]:
df.dtypes

Date       str
Time       str
Sales    int64
dtype: object

***2_converting the date and time columns to datetime formate***

In [6]:
df['Date']=pd.to_datetime(df['Date'])

In [8]:
df.dtypes
df.head()

        Date                Time  Sales
0 2026-01-15 2026-10-14 09:30:00   2000
1 2026-02-20 2026-10-14 14:45:00   3500
2 2026-03-10 2026-10-14 18:20:00   1800
3 2026-04-25 2026-10-14 10:15:00   4200
4 2026-05-05 2026-10-14 21:50:00   3000

***3_Now Extracting month, day and year from Date column***

In [9]:
df['year']=df['Date'].dt.year
df['month']=df['Date'].dt.month
df['day']=df['Date'].dt.day
df['day of week']=df['Date'].dt.dayofweek

In [10]:
df.head()

        Date                Time  Sales  year  month  day  day of week
0 2026-01-15 2026-10-14 09:30:00   2000  2026      1   15            3
1 2026-02-20 2026-10-14 14:45:00   3500  2026      2   20            4
2 2026-03-10 2026-10-14 18:20:00   1800  2026      3   10            1
3 2026-04-25 2026-10-14 10:15:00   4200  2026      4   25            5
4 2026-05-05 2026-10-14 21:50:00   3000  2026      5    5            1

***4_now convert the time column to proper formate***

In [12]:
df['Time']=pd.to_datetime(df['Time'],format='%H:%M:%S')

***5_Now lets hour and minute***

In [15]:
df['Hour']=df['Time'].dt.hour
df['Minute']=df['Time'].dt.hour

In [16]:
df.head()

,Date,Time,Sales,year,month,day,day of week,Hour,Minute
0,2026-01-15,2026-10-14 09:30:00,2000,2026,1,15,3,9,9
1,2026-02-20,2026-10-14 14:45:00,3500,2026,2,20,4,14,14
2,2026-03-10,2026-10-14 18:20:00,1800,2026,3,10,1,18,18
3,2026-04-25,2026-10-14 10:15:00,4200,2026,4,25,5,10,10
4,2026-05-05,2026-10-14 21:50:00,3000,2026,5,5,1,21,21